import { GamePlant } from "../models/game-plant.interface";

export const GAME_OBJECT_PLANT_LIST: GamePlant[] = [
    {
        id: "game_object_wheat",
        label: "Wheat",
        buyPrice: 5,
        sellPrice: 10,
        experience: 3,
        requiredLevel: 1,
        growTime: 60,
        imageUrl: "path/to/wheat_image.png",
    },
    {
        id: "game_object_corn",
        label: "Corn",
        buyPrice: 8,
        sellPrice: 15,
        experience: 5,
        requiredLevel: 2,
        growTime: 90,
        imageUrl: "path/to/corn_image.png",
    },
    {
        id: "game_object_soybeans",
        label: "Soybean",
        buyPrice: 12,
        sellPrice: 25,
        experience: 10,
        requiredLevel: 4,
        growTime: 120,
        imageUrl: "path/to/soybeans_image.png",
    },
    {
        id: "game_object_potatoes",
        label: "Potato",
        buyPrice: 9,
        sellPrice: 18,
        experience: 6,
        requiredLevel: 3,
        growTime: 75,
        imageUrl: "path/to/potatoes_image.png",
    },
    {
        id: "game_object_sugar_beets",
        label: "Sugar Beet",
        buyPrice: 11,
        sellPrice: 22,
        experience: 8,
        requiredLevel: 4,
        growTime: 100,
        imageUrl: "path/to/sugar_beets_image.png",
    },
    {
        id: "game_object_sunflowers",
        label: "Sunflower",
        buyPrice: 14,
        sellPrice: 28,
        experience: 12,
        requiredLevel: 5,
        growTime: 150,
        imageUrl: "path/to/sunflowers_image.png",
    },
    {
        id: "game_object_lettuce",
        label: "Lettuce",
        buyPrice: 7,
        sellPrice: 14,
        experience: 5,
        requiredLevel: 3,
        growTime: 50,
        imageUrl: "path/to/lettuce_image.png",
    },
    {
        id: "game_object_carrots",
        label: "Carrot",
        buyPrice: 8,
        sellPrice: 16,
        experience: 6,
        requiredLevel: 3,
        growTime: 70,
        imageUrl: "path/to/carrots_image.png",
    },
    {
        id: "game_object_onions",
        label: "Onion",
        buyPrice: 6,
        sellPrice: 12,
        experience: 4,
        requiredLevel: 4,
        growTime: 80,
        imageUrl: "path/to/onions_image.png",
    },
    {
        id: "game_object_tomatoes",
        label: "Tomato",
        buyPrice: 9,
        sellPrice: 18,
        experience: 7,
        requiredLevel: 3,
        growTime: 65,
        imageUrl: "path/to/tomatoes_image.png",
    },
    {
        id: "game_object_cabbage",
        label: "Cabbage",
        buyPrice: 7,
        sellPrice: 14,
        experience: 5,
        requiredLevel: 3,
        growTime: 55,
        imageUrl: "path/to/cabbage_image.png",
    },
    {
        id: "game_object_sugarcane",
        label: "Sugarcane",
        buyPrice: 15,
        sellPrice: 30,
        experience: 13,
        requiredLevel: 8,
        growTime: 180,
        imageUrl: "path/to/sugarcane_image.png",
    },
    {
        id: "game_object_cucumbers",
        label: "Cucumber",
        buyPrice: 9,
        sellPrice: 18,
        experience: 7,
        requiredLevel: 3,
        growTime: 85,
        imageUrl: "path/to/cucumbers_image.png",
    },
    {
        id: "game_object_bell_peppers",
        label: "Bell Pepper",
        buyPrice: 10,
        sellPrice: 20,
        experience: 8,
        requiredLevel: 4,
        growTime: 95,
        imageUrl: "path/to/bell_peppers_image.png",
    },
];
